[package]
name = "auto-konsole"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
home = "0.5.12"
tokio = { version = "1.48.0", features = ["full"] }
toml = "0.9.8"
zbus = { version = "5.12.0", default-features = false, features = ["tokio"] }
